[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

# [context.dev.environment]
  # VITE_APP_BASE_URL="https://dev--cactos-host.netlify.app/"
  # VITE_APP_CACTOS_TOOLS="https://dev--cactos-tools.netlify.app/"
  # VITE_APP_CACTOS_ASSISTANT="https://dev--cactos-assistant.netlify.app/"
  # VITE_APP_CACTOS_FINANCING="https://dev--cactos-financing.netlify.app/"
  # VITE_APP_CLERK_PUBLISHABLE_KEY="pk_test_ZnVua3ktdGFkcG9sZS01LmNsZXJrLmFjY291bnRzLmRldiQ"
  # VITE_APP_CLERK_SECRET_KEY="sk_test_XTrsN21g3SeCNHolV9eqSGxPmMwjTC4PyY8F1XTEHd"
  # VITE_APP_OPENAI_API_KEY="sk-proj-yjNNzQWcYYily1Aa4kHJT3BlbkFJ168oGx6seVNlh3wukbwv"
  # VITE_APP_UPLOADTHING_SECRET="sk_live_be12c0fb8af92a2d2d3b001e8a70bfd9d45a9ae6904cf7d30ebc5f6e89562628"
  # VITE_APP_UPLOADTHING_APP_ID="5ctujju0tt"

[context.production.environment]
  VITE_APP_BASE_URL="https://cactos-host.netlify.app/"
  VITE_APP_CACTOS_TOOLS="https://cactos-tools.netlify.app/assets/remoteEntry.js"
  VITE_APP_CACTOS_ASSISTANT="https://cactos-assistant.netlify.app/assets/remoteEntry.js"
  VITE_APP_CACTOS_FINANCING="https://cactos-financing.netlify.app/assets/remoteEntry.js"
  VITE_APP_CLERK_PUBLISHABLE_KEY="pk_test_ZnVua3ktdGFkcG9sZS01LmNsZXJrLmFjY291bnRzLmRldiQ"
  VITE_APP_CLERK_SECRET_KEY="sk_test_XTrsN21g3SeCNHolV9eqSGxPmMwjTC4PyY8F1XTEHd"
  VITE_APP_OPENAI_API_KEY="sk-proj-yjNNzQWcYYily1Aa4kHJT3BlbkFJ168oGx6seVNlh3wukbwv"
  VITE_APP_UPLOADTHING_SECRET="sk_live_be12c0fb8af92a2d2d3b001e8a70bfd9d45a9ae6904cf7d30ebc5f6e89562628"
  VITE_APP_UPLOADTHING_APP_ID="5ctujju0tt"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200


